#!/usr/bin/env perl

use strict;
use warnings;

sub on_user_command
{
    my ($self, $cmd) = @_;

    if ($cmd eq "my-extension:test") {
        show_something($self);
    }
}

sub on_action
{

    my ($self, $action, $term) = @_;

    if ($action eq "test") {
        $term->scr_add_lines("\r\nHello World!");
    }
}
